networks:
  vpndogs:
    name: vpndogs

x-singbox: &singbox
  image: ghcr.io/nimaboubanian/sing-box-client:latest
  networks: [vpndogs]
  restart: unless-stopped

services:
  sb1:
    <<: *singbox
    container_name: sb1
    environment:
      SUB_URL: ${SUB_URL_1:?required}
      FINAL_TAG: ${FINAL_TAG_1:-}
      LOG_LEVEL: ${LOG_LEVEL:-warn}
      RESTART_INTERVAL: ${RESTART_INTERVAL:-0}
  sb2:
    <<: *singbox
    container_name: sb2
    environment:
      SUB_URL: ${SUB_URL_2:?required}
      FINAL_TAG: ${FINAL_TAG_2:-}
      LOG_LEVEL: ${LOG_LEVEL:-warn}
      RESTART_INTERVAL: ${RESTART_INTERVAL:-0}
  sb3:
    <<: *singbox
    container_name: sb3
    environment:
      SUB_URL: ${SUB_URL_3:?required}
      FINAL_TAG: ${FINAL_TAG_3:-}
      LOG_LEVEL: ${LOG_LEVEL:-warn}
      RESTART_INTERVAL: ${RESTART_INTERVAL:-0}
  sb4:
    <<: *singbox
    container_name: sb4
    environment:
      SUB_URL: ${SUB_URL_4:?required}
      FINAL_TAG: ${FINAL_TAG_4:-}
      LOG_LEVEL: ${LOG_LEVEL:-warn}
      RESTART_INTERVAL: ${RESTART_INTERVAL:-0}

  lb:
    image: ghcr.io/nimaboubanian/sing-box-lb:latest
    container_name: sb-lb
    networks: [vpndogs]
    ports:
      - "127.0.0.1:1081:1081"
    depends_on: [sb1, sb2, sb3, sb4]
    restart: unless-stopped
